# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sphinx doc build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest:latest
    

    steps:
    - uses: actions/checkout@v3
    
    
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/source"
        build-command: "sphinx-build -b html . _build"
  build2:
    runs-on: ubuntu-latest:latest
    container:
      image: minidocks/sphinx-doc:latest
      volumes: 
        - /home/runner/work/rtdTutorial/rtdTutorial/docs/source:/doc
    steps:
      - uses: actions/checkout@v3
      - name: build doc
        run: (sphinx-quickstart .)
        
    
